/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiDepositRouteImport } from './routes/api/deposit'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiPhoneLoginRouteImport } from './routes/api/phone-login'
import { Route as ApiPlayRouteImport } from './routes/api/play'
import { Route as ApiRedeemCouponRouteImport } from './routes/api/redeem-coupon'
import { Route as ApiStaffRouteImport } from './routes/api/staff'
import { Route as ApiStaffCouponRouteImport } from './routes/api/staff-coupon'
import { Route as ApiWithdrawRouteImport } from './routes/api/withdraw'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppDepositRouteImport } from './routes/app/deposit'
import { Route as AppFootballRouteImport } from './routes/app/football'
import { Route as AppGamesRouteImport } from './routes/app/games'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppLotteryRouteImport } from './routes/app/lottery'
import { Route as AppLuckyRouteImport } from './routes/app/lucky'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPromoRouteImport } from './routes/app/promo'
import { Route as AppRatesRouteImport } from './routes/app/rates'
import { Route as AppResultsRouteImport } from './routes/app/results'
import { Route as AppSlotRouteImport } from './routes/app/slot'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminSplatRouteImport } from './routes/app/admin/$'
import { Route as AppAdminDrawsRouteImport } from './routes/app/admin/draws'
import { Route as AppAdminMembersRouteImport } from './routes/app/admin/members'
import { Route as AppAdminPromosRouteImport } from './routes/app/admin/promos'
import { Route as AppAdminRtpRouteImport } from './routes/app/admin/rtp'
import { Route as AppAdminWheelRouteImport } from './routes/app/admin/wheel'
import { Route as AppAdminWithdrawRouteImport } from './routes/app/admin/withdraw'
import { Route as AppGamesIndexRouteImport } from './routes/app/games/index'
import { Route as AppGamesIdRouteImport } from './routes/app/games/$id'
import { Route as AppLotteryIndexRouteImport } from './routes/app/lottery/index'
import { Route as AppLotteryIdRouteImport } from './routes/app/lottery/$id'
import { Route as AppSlotIndexRouteImport } from './routes/app/slot/index'
import { Route as AppSlotIdRouteImport } from './routes/app/slot/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiDepositRoute = ApiDepositRouteImport.update({
  id: '/api/deposit',
  path: '/api/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneLoginRoute = ApiPhoneLoginRouteImport.update({
  id: '/api/phone-login',
  path: '/api/phone-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayRoute = ApiPlayRouteImport.update({
  id: '/api/play',
  path: '/api/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedeemCouponRoute = ApiRedeemCouponRouteImport.update({
  id: '/api/redeem-coupon',
  path: '/api/redeem-coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffRoute = ApiStaffRouteImport.update({
  id: '/api/staff',
  path: '/api/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffCouponRoute = ApiStaffCouponRouteImport.update({
  id: '/api/staff-coupon',
  path: '/api/staff-coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawRoute = ApiWithdrawRouteImport.update({
  id: '/api/withdraw',
  path: '/api/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppFootballRoute = AppFootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLotteryRoute = AppLotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => AppRoute,
} as any)
const AppLuckyRoute = AppLuckyRouteImport.update({
  id: '/lucky',
  path: '/lucky',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPromoRoute = AppPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotRoute = AppSlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSplatRoute = AppAdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDrawsRoute = AppAdminDrawsRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPromosRoute = AppAdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRtpRoute = AppAdminRtpRouteImport.update({
  id: '/rtp',
  path: '/rtp',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminWheelRoute = AppAdminWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminWithdrawRoute = AppAdminWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppLotteryIndexRoute = AppLotteryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLotteryRoute,
} as any)
const AppLotteryIdRoute = AppLotteryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLotteryRoute,
} as any)
const AppSlotIndexRoute = AppSlotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlotRoute,
} as any)
const AppSlotIdRoute = AppSlotIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSlotRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/phone-login': typeof ApiPhoneLoginRoute
  '/api/play': typeof ApiPlayRoute
  '/api/redeem-coupon': typeof ApiRedeemCouponRoute
  '/api/staff': typeof ApiStaffRoute
  '/api/staff-coupon': typeof ApiStaffCouponRoute
  '/api/withdraw': typeof ApiWithdrawRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/deposit': typeof AppDepositRoute
  '/app/football': typeof AppFootballRoute
  '/app/games': typeof AppGamesRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/lottery': typeof AppLotteryRouteWithChildren
  '/app/lucky': typeof AppLuckyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promo': typeof AppPromoRoute
  '/app/rates': typeof AppRatesRoute
  '/app/results': typeof AppResultsRoute
  '/app/slot': typeof AppSlotRouteWithChildren
  '/app/staff': typeof AppStaffRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/admin/$': typeof AppAdminSplatRoute
  '/app/admin/draws': typeof AppAdminDrawsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/promos': typeof AppAdminPromosRoute
  '/app/admin/rtp': typeof AppAdminRtpRoute
  '/app/admin/wheel': typeof AppAdminWheelRoute
  '/app/admin/withdraw': typeof AppAdminWithdrawRoute
  '/app/games/$id': typeof AppGamesIdRoute
  '/app/lottery/$id': typeof AppLotteryIdRoute
  '/app/slot/$id': typeof AppSlotIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/games/': typeof AppGamesIndexRoute
  '/app/lottery/': typeof AppLotteryIndexRoute
  '/app/slot/': typeof AppSlotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/phone-login': typeof ApiPhoneLoginRoute
  '/api/play': typeof ApiPlayRoute
  '/api/redeem-coupon': typeof ApiRedeemCouponRoute
  '/api/staff': typeof ApiStaffRoute
  '/api/staff-coupon': typeof ApiStaffCouponRoute
  '/api/withdraw': typeof ApiWithdrawRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/football': typeof AppFootballRoute
  '/app/history': typeof AppHistoryRoute
  '/app/lucky': typeof AppLuckyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promo': typeof AppPromoRoute
  '/app/rates': typeof AppRatesRoute
  '/app/results': typeof AppResultsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/admin/$': typeof AppAdminSplatRoute
  '/app/admin/draws': typeof AppAdminDrawsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/promos': typeof AppAdminPromosRoute
  '/app/admin/rtp': typeof AppAdminRtpRoute
  '/app/admin/wheel': typeof AppAdminWheelRoute
  '/app/admin/withdraw': typeof AppAdminWithdrawRoute
  '/app/games/$id': typeof AppGamesIdRoute
  '/app/lottery/$id': typeof AppLotteryIdRoute
  '/app/slot/$id': typeof AppSlotIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/games': typeof AppGamesIndexRoute
  '/app/lottery': typeof AppLotteryIndexRoute
  '/app/slot': typeof AppSlotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/phone-login': typeof ApiPhoneLoginRoute
  '/api/play': typeof ApiPlayRoute
  '/api/redeem-coupon': typeof ApiRedeemCouponRoute
  '/api/staff': typeof ApiStaffRoute
  '/api/staff-coupon': typeof ApiStaffCouponRoute
  '/api/withdraw': typeof ApiWithdrawRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/deposit': typeof AppDepositRoute
  '/app/football': typeof AppFootballRoute
  '/app/games': typeof AppGamesRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/lottery': typeof AppLotteryRouteWithChildren
  '/app/lucky': typeof AppLuckyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promo': typeof AppPromoRoute
  '/app/rates': typeof AppRatesRoute
  '/app/results': typeof AppResultsRoute
  '/app/slot': typeof AppSlotRouteWithChildren
  '/app/staff': typeof AppStaffRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/admin/$': typeof AppAdminSplatRoute
  '/app/admin/draws': typeof AppAdminDrawsRoute
  '/app/admin/members': typeof AppAdminMembersRoute
  '/app/admin/promos': typeof AppAdminPromosRoute
  '/app/admin/rtp': typeof AppAdminRtpRoute
  '/app/admin/wheel': typeof AppAdminWheelRoute
  '/app/admin/withdraw': typeof AppAdminWithdrawRoute
  '/app/games/$id': typeof AppGamesIdRoute
  '/app/lottery/$id': typeof AppLotteryIdRoute
  '/app/slot/$id': typeof AppSlotIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/games/': typeof AppGamesIndexRoute
  '/app/lottery/': typeof AppLotteryIndexRoute
  '/app/slot/': typeof AppSlotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/rates'
    | '/register'
    | '/reset'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/api/deposit'
    | '/api/logout'
    | '/api/phone-login'
    | '/api/play'
    | '/api/redeem-coupon'
    | '/api/staff'
    | '/api/staff-coupon'
    | '/api/withdraw'
    | '/app/admin'
    | '/app/deposit'
    | '/app/football'
    | '/app/games'
    | '/app/history'
    | '/app/lottery'
    | '/app/lucky'
    | '/app/profile'
    | '/app/promo'
    | '/app/rates'
    | '/app/results'
    | '/app/slot'
    | '/app/staff'
    | '/app/wallet'
    | '/app/withdraw'
    | '/articles/$slug'
    | '/admin/'
    | '/app/'
    | '/articles/'
    | '/api/auth/$'
    | '/app/admin/$'
    | '/app/admin/draws'
    | '/app/admin/members'
    | '/app/admin/promos'
    | '/app/admin/rtp'
    | '/app/admin/wheel'
    | '/app/admin/withdraw'
    | '/app/games/$id'
    | '/app/lottery/$id'
    | '/app/slot/$id'
    | '/app/admin/'
    | '/app/games/'
    | '/app/lottery/'
    | '/app/slot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rates'
    | '/register'
    | '/reset'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/api/deposit'
    | '/api/logout'
    | '/api/phone-login'
    | '/api/play'
    | '/api/redeem-coupon'
    | '/api/staff'
    | '/api/staff-coupon'
    | '/api/withdraw'
    | '/app/deposit'
    | '/app/football'
    | '/app/history'
    | '/app/lucky'
    | '/app/profile'
    | '/app/promo'
    | '/app/rates'
    | '/app/results'
    | '/app/staff'
    | '/app/wallet'
    | '/app/withdraw'
    | '/articles/$slug'
    | '/admin'
    | '/app'
    | '/articles'
    | '/api/auth/$'
    | '/app/admin/$'
    | '/app/admin/draws'
    | '/app/admin/members'
    | '/app/admin/promos'
    | '/app/admin/rtp'
    | '/app/admin/wheel'
    | '/app/admin/withdraw'
    | '/app/games/$id'
    | '/app/lottery/$id'
    | '/app/slot/$id'
    | '/app/admin'
    | '/app/games'
    | '/app/lottery'
    | '/app/slot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/rates'
    | '/register'
    | '/reset'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/api/deposit'
    | '/api/logout'
    | '/api/phone-login'
    | '/api/play'
    | '/api/redeem-coupon'
    | '/api/staff'
    | '/api/staff-coupon'
    | '/api/withdraw'
    | '/app/admin'
    | '/app/deposit'
    | '/app/football'
    | '/app/games'
    | '/app/history'
    | '/app/lottery'
    | '/app/lucky'
    | '/app/profile'
    | '/app/promo'
    | '/app/rates'
    | '/app/results'
    | '/app/slot'
    | '/app/staff'
    | '/app/wallet'
    | '/app/withdraw'
    | '/articles/$slug'
    | '/admin/'
    | '/app/'
    | '/articles/'
    | '/api/auth/$'
    | '/app/admin/$'
    | '/app/admin/draws'
    | '/app/admin/members'
    | '/app/admin/promos'
    | '/app/admin/rtp'
    | '/app/admin/wheel'
    | '/app/admin/withdraw'
    | '/app/games/$id'
    | '/app/lottery/$id'
    | '/app/slot/$id'
    | '/app/admin/'
    | '/app/games/'
    | '/app/lottery/'
    | '/app/slot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RatesRoute: typeof RatesRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiDepositRoute: typeof ApiDepositRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiPhoneLoginRoute: typeof ApiPhoneLoginRoute
  ApiPlayRoute: typeof ApiPlayRoute
  ApiRedeemCouponRoute: typeof ApiRedeemCouponRoute
  ApiStaffRoute: typeof ApiStaffRoute
  ApiStaffCouponRoute: typeof ApiStaffCouponRoute
  ApiWithdrawRoute: typeof ApiWithdrawRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/deposit': {
      id: '/api/deposit'
      path: '/api/deposit'
      fullPath: '/api/deposit'
      preLoaderRoute: typeof ApiDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone-login': {
      id: '/api/phone-login'
      path: '/api/phone-login'
      fullPath: '/api/phone-login'
      preLoaderRoute: typeof ApiPhoneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/play': {
      id: '/api/play'
      path: '/api/play'
      fullPath: '/api/play'
      preLoaderRoute: typeof ApiPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redeem-coupon': {
      id: '/api/redeem-coupon'
      path: '/api/redeem-coupon'
      fullPath: '/api/redeem-coupon'
      preLoaderRoute: typeof ApiRedeemCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff': {
      id: '/api/staff'
      path: '/api/staff'
      fullPath: '/api/staff'
      preLoaderRoute: typeof ApiStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff-coupon': {
      id: '/api/staff-coupon'
      path: '/api/staff-coupon'
      fullPath: '/api/staff-coupon'
      preLoaderRoute: typeof ApiStaffCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdraw': {
      id: '/api/withdraw'
      path: '/api/withdraw'
      fullPath: '/api/withdraw'
      preLoaderRoute: typeof ApiWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/football': {
      id: '/app/football'
      path: '/football'
      fullPath: '/app/football'
      preLoaderRoute: typeof AppFootballRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lottery': {
      id: '/app/lottery'
      path: '/lottery'
      fullPath: '/app/lottery'
      preLoaderRoute: typeof AppLotteryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lucky': {
      id: '/app/lucky'
      path: '/lucky'
      fullPath: '/app/lucky'
      preLoaderRoute: typeof AppLuckyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promo': {
      id: '/app/promo'
      path: '/promo'
      fullPath: '/app/promo'
      preLoaderRoute: typeof AppPromoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rates': {
      id: '/app/rates'
      path: '/rates'
      fullPath: '/app/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/slot': {
      id: '/app/slot'
      path: '/slot'
      fullPath: '/app/slot'
      preLoaderRoute: typeof AppSlotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/$': {
      id: '/app/admin/$'
      path: '/$'
      fullPath: '/app/admin/$'
      preLoaderRoute: typeof AppAdminSplatRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/draws': {
      id: '/app/admin/draws'
      path: '/draws'
      fullPath: '/app/admin/draws'
      preLoaderRoute: typeof AppAdminDrawsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/members': {
      id: '/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/promos': {
      id: '/app/admin/promos'
      path: '/promos'
      fullPath: '/app/admin/promos'
      preLoaderRoute: typeof AppAdminPromosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/rtp': {
      id: '/app/admin/rtp'
      path: '/rtp'
      fullPath: '/app/admin/rtp'
      preLoaderRoute: typeof AppAdminRtpRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/wheel': {
      id: '/app/admin/wheel'
      path: '/wheel'
      fullPath: '/app/admin/wheel'
      preLoaderRoute: typeof AppAdminWheelRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/withdraw': {
      id: '/app/admin/withdraw'
      path: '/withdraw'
      fullPath: '/app/admin/withdraw'
      preLoaderRoute: typeof AppAdminWithdrawRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/games/': {
      id: '/app/games/'
      path: '/'
      fullPath: '/app/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/app/games/$id': {
      id: '/app/games/$id'
      path: '/$id'
      fullPath: '/app/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/app/lottery/': {
      id: '/app/lottery/'
      path: '/'
      fullPath: '/app/lottery/'
      preLoaderRoute: typeof AppLotteryIndexRouteImport
      parentRoute: typeof AppLotteryRoute
    }
    '/app/lottery/$id': {
      id: '/app/lottery/$id'
      path: '/$id'
      fullPath: '/app/lottery/$id'
      preLoaderRoute: typeof AppLotteryIdRouteImport
      parentRoute: typeof AppLotteryRoute
    }
    '/app/slot/': {
      id: '/app/slot/'
      path: '/'
      fullPath: '/app/slot/'
      preLoaderRoute: typeof AppSlotIndexRouteImport
      parentRoute: typeof AppSlotRoute
    }
    '/app/slot/$id': {
      id: '/app/slot/$id'
      path: '/$id'
      fullPath: '/app/slot/$id'
      preLoaderRoute: typeof AppSlotIdRouteImport
      parentRoute: typeof AppSlotRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAdminRouteChildren {
  AppAdminSplatRoute: typeof AppAdminSplatRoute
  AppAdminDrawsRoute: typeof AppAdminDrawsRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminPromosRoute: typeof AppAdminPromosRoute
  AppAdminRtpRoute: typeof AppAdminRtpRoute
  AppAdminWheelRoute: typeof AppAdminWheelRoute
  AppAdminWithdrawRoute: typeof AppAdminWithdrawRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminSplatRoute: AppAdminSplatRoute,
  AppAdminDrawsRoute: AppAdminDrawsRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminPromosRoute: AppAdminPromosRoute,
  AppAdminRtpRoute: AppAdminRtpRoute,
  AppAdminWheelRoute: AppAdminWheelRoute,
  AppAdminWithdrawRoute: AppAdminWithdrawRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppGamesRouteChildren {
  AppGamesIdRoute: typeof AppGamesIdRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesIdRoute: AppGamesIdRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(
  AppGamesRouteChildren,
)

interface AppLotteryRouteChildren {
  AppLotteryIdRoute: typeof AppLotteryIdRoute
  AppLotteryIndexRoute: typeof AppLotteryIndexRoute
}

const AppLotteryRouteChildren: AppLotteryRouteChildren = {
  AppLotteryIdRoute: AppLotteryIdRoute,
  AppLotteryIndexRoute: AppLotteryIndexRoute,
}

const AppLotteryRouteWithChildren = AppLotteryRoute._addFileChildren(
  AppLotteryRouteChildren,
)

interface AppSlotRouteChildren {
  AppSlotIdRoute: typeof AppSlotIdRoute
  AppSlotIndexRoute: typeof AppSlotIndexRoute
}

const AppSlotRouteChildren: AppSlotRouteChildren = {
  AppSlotIdRoute: AppSlotIdRoute,
  AppSlotIndexRoute: AppSlotIndexRoute,
}

const AppSlotRouteWithChildren =
  AppSlotRoute._addFileChildren(AppSlotRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDepositRoute: typeof AppDepositRoute
  AppFootballRoute: typeof AppFootballRoute
  AppGamesRoute: typeof AppGamesRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppLotteryRoute: typeof AppLotteryRouteWithChildren
  AppLuckyRoute: typeof AppLuckyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPromoRoute: typeof AppPromoRoute
  AppRatesRoute: typeof AppRatesRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSlotRoute: typeof AppSlotRouteWithChildren
  AppStaffRoute: typeof AppStaffRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDepositRoute: AppDepositRoute,
  AppFootballRoute: AppFootballRoute,
  AppGamesRoute: AppGamesRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppLotteryRoute: AppLotteryRouteWithChildren,
  AppLuckyRoute: AppLuckyRoute,
  AppProfileRoute: AppProfileRoute,
  AppPromoRoute: AppPromoRoute,
  AppRatesRoute: AppRatesRoute,
  AppResultsRoute: AppResultsRoute,
  AppSlotRoute: AppSlotRouteWithChildren,
  AppStaffRoute: AppStaffRoute,
  AppWalletRoute: AppWalletRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RatesRoute: RatesRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiDepositRoute: ApiDepositRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiPhoneLoginRoute: ApiPhoneLoginRoute,
  ApiPlayRoute: ApiPlayRoute,
  ApiRedeemCouponRoute: ApiRedeemCouponRoute,
  ApiStaffRoute: ApiStaffRoute,
  ApiStaffCouponRoute: ApiStaffCouponRoute,
  ApiWithdrawRoute: ApiWithdrawRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
